### ISSUE TITLE
examples panic 

### ISSUE THREAD

**Issue by ghost** [omni-viral/xfg-rs#12]
command 
`cargo run --example pbm --features vulkan`

environment:
OS: Windows 10
rustc 1.30.0-nightly (33b923fd4 2018-08-18)
cargo 1.29.0-nightly (6a7672ef5 2018-08-14)

result:
`
results in panic:
thread 'main' panicked at 'Unhandled error in XfgDescriptorPool: Device memory allocation failed.', examples\pbm\../common/lib.rs:128:33
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'Values of this type can't be dropped!',
`

expected: example is running

**Comment by zakarumych** [comment]
Could you post backtrace as well?
I can't test on vulkan ATM.

**Comment by ghost** [comment]
Note: dx12 has a not implemented issue, but to test it I had to add 'dx12 = ["gfx-render/gfx-backend-dx12"] to the cargo.toml

`thread 'main' panicked at 'not yet implemented', [...]gfx-e86e7f3ebdbc4218\6cb2a80\src\backend\dx12\src\command.rs:1928:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'Allocator must be cleared: SmartAllocator `

**Comment by zakarumych** [comment]
This panic seems to be triggered at exit.

**Comment by ghost** [comment]
backtrace:
[log.txt](https://github.com/omni-viral/xfg-rs/files/2419470/log.txt)

**Comment by ghost** [comment]
with set RUST_BACKTRACE=1
[log.txt](https://github.com/omni-viral/xfg-rs/files/2419482/log.txt)

**Comment by zakarumych** [comment]
I see that on Vulkan you get "out of device memory" error on descriptor set allocation. This is strange.

**Comment by ghost** [comment]
I've tried it on another windows10 machine with the same result.
Here is a more  detailed log (trace turned on
). I see nothing special in it.

[log.txt](https://github.com/omni-viral/xfg-rs/files/2426233/log.txt)

(Both of them had NVIDIA cards, I will give it a try with ATI card too if I get to that pc)
*EDIT*: An the ATI card it is working.

**Comment by zakarumych** [comment]
I'll try to investigate today. Got my hands on machine with windows
